services:
  tracktor:
    build:
      context: .
      dockerfile: Dockerfile
    #image: ghcr.io/rizwxxn/tracktor-plus:latest
    container_name: tracktor-plus
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - tracktor-plus:/data
    environment:
      - PUBLIC_DEMO_MODE=false
      - FORCE_DATA_SEED=false
      - CORS_ORIGINS="http://localhost:3000"
      - TRUST_PROXY=true
      - UPLOADS_DIR=/data/uploads

volumes:
  tracktor-plus:
    name: tracktor-plus
