import PDFDocument from 'pdfkit';
import type { MaintenanceLog } from '$lib/domain/maintenance';
import { format } from 'date-fns';

interface VehicleInfo {
  licensePlate: string;
  name: string;
}

export const generateMaintenanceLogsPdf = (
  maintenanceLogs: MaintenanceLog[],
  vehicleInfo: VehicleInfo
): Promise<Buffer> => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const chunks: Buffer[] = [];

      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      doc.fontSize(20).text('Maintenance Log Report', { align: 'center' });
      doc.moveDown();
      doc.fontSize(12).text(`Vehicle: ${vehicleInfo.name} (${vehicleInfo.licensePlate})`, {
        align: 'center'
      });
      doc.text(`Generated: ${format(new Date(), 'yyyy-MM-dd HH:mm')}`, { align: 'center' });
      doc.moveDown(2);

      if (maintenanceLogs.length === 0) {
        doc.fontSize(12).text('No maintenance records found.', { align: 'center' });
      } else {
        const tableTop = 180;
        let y = tableTop;

        doc.fontSize(10).font('Helvetica-Bold');
        doc.text('Date', 50, y, { width: 80 });
        doc.text('Odometer', 130, y, { width: 70 });
        doc.text('Service Center', 200, y, { width: 120 });
        doc.text('Cost', 320, y, { width: 60 });
        doc.text('Notes', 380, y, { width: 200 });

        doc
          .moveTo(50, y + 15)
          .lineTo(580, y + 15)
          .stroke();

        y += 25;
        doc.font('Helvetica').fontSize(9);

        for (const log of maintenanceLogs) {
          if (y > 700) {
            doc.addPage();
            y = 50;
          }

          const dateStr = log.date ? format(new Date(log.date), 'yyyy-MM-dd') : '-';
          const odometerStr = log.odometer ? log.odometer.toString() : '-';
          const serviceCenterStr = log.serviceCenter || '-';
          const costStr = log.cost ? `$${log.cost.toFixed(2)}` : '-';
          const notesStr = log.notes || '-';

          doc.text(dateStr, 50, y, { width: 80 });
          doc.text(odometerStr, 130, y, { width: 70 });
          doc.text(serviceCenterStr.substring(0, 20), 200, y, { width: 120 });
          doc.text(costStr, 320, y, { width: 60 });
          doc.text(notesStr.substring(0, 40), 380, y, { width: 200 });

          y += 20;
        }
      }

      doc.moveDown(2);
      doc.fontSize(8).text('Generated by Tracktor', { align: 'center' });

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};
